apiVersion: v1 # required
kind: Pod # required
metadata: # required
 name: servidor-web # required
 labels:
   service: web
spec: # required
 containers:
   - image: roxsross12/k8s_test_web:latest
     name: contenedor
     imagePullPolicy: Always
     ports:
        - containerPort: 80